server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cn-cd-dx-6.natfrp.cloud:60065/demo_database?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/demo_database?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Root_12root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
  # 这个东西很神奇，不加就报错，不信你试试（
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mybatis/xml/*.xml





